sig-scalability/watch-list: use n2 machine types for master instances
At the moment the tests fail with:

ERROR: (gcloud.compute.instances.create) Could not fetch resource:
 - The selected machine type (n1-standard-32) is not compatible with CPU platform icelake
Failed to create master instance due to non-retryable error

Possibly caused by kubernetes/kubernetes#118626

https://cloud.google.com/compute/docs/general-purpose-machines#n2_series